# Default values for Silver Layer SparkApplication template

job_id: "dag-run-{{ dag_run_id }}"
input_table: "bronze.taxi_trips" # Source table from bronze layer
output_table: "taxi_trips_clean" # Target table in silver warehouse

sparkVersion: "3.5.0"
pythonVersion: "3"

image: "hungvt0110/ingestion-job:latest"
imagePullPolicy: "Always"

driver:
  cores: 1
  coreLimit: "1200m"
  memory: "2g"
  memoryOverhead: "512m"

executor:
  cores: 2
  instances: 3
  memory: "4g"
  memoryOverhead: "1g"

env:
  SPARK_MINOR_VERSION: "3.5"
  ICEBERG_VERSION: "1.5.2"
  CATALOG_URL: "http://openhouse-lakekeeper:8181/catalog"
  CLIENT_ID: "spark"
  CLIENT_SECRET: "UoLrOodDp6idyOh1wryGPpzJWlPMX0Td"
  WAREHOUSE: "silver"
  KEYCLOAK_TOKEN_ENDPOINT: "http://openhouse-keycloak:80/realms/iceberg/protocol/openid-connect/token"
  AWS_ACCESS_KEY_ID: "admin"
  AWS_SECRET_ACCESS_KEY: "admin123"

serviceAccount: "openhouse-spark-operator-spark"
namespace: "data-platform"

restartPolicy:
  type: "Never"
  onFailureRetries: 2
  onFailureRetryInterval: 10
  onSubmissionFailureRetries: 3
  onSubmissionFailureRetryInterval: 20

timeToLiveSeconds: 3600
